// <auto-generated />
namespace WebApplicationFloreria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fk_creadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fk_creadas));
        
        string IMigrationMetadata.Id
        {
            get { return "201906102312017_fk_creadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
